Further tweaks
zktuong/dandelion pull request #194
Opened 2022-10-12 12:57 UTC by ktpolanski

Commit names self explanatory

2022-10-12 13:08 UTC, zktuong commented on requirements.txt
> +git+https://github.com/zktuong/nxviz.git@custom_color_mapping_circos_nodes_and_edges
I think uploading to pypi will throw and error because of this.

https://stackoverflow.com/questions/54887301/how-can-i-use-git-repos-as-dependencies-for-my-pypi-package

2022-10-12 13:10 UTC, zktuong commented on requirements.txt
> +git+https://github.com/zktuong/nxviz.git@custom_color_mapping_circos_nodes_and_edges
in fact it's throwing an error during install already:
https://github.com/zktuong/dandelion/actions/runs/3234865044/jobs/5298512983#step:17:29
```
      error in sc-dandelion setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Parse error at "'+https:/'": Expected string_end
```

2022-10-12 13:28 UTC, ktpolanski commented on requirements.txt
> +git+https://github.com/zktuong/nxviz.git@custom_color_mapping_circos_nodes_and_edges
F

2022-10-12 14:31 UTC, zktuong requested changes

2022-10-12 14:31 UTC, zktuong commented on container/dandelion_preprocess.py
> -        default="filtered",
ok this is throwing the error in the container test
https://github.com/zktuong/dandelion/actions/runs/3235188994/jobs/5299275829#step:8:260

so perhaps these files have to be renamed:
https://github.com/zktuong/dandelion/tree/master/container/tests/sample_test_10x

2022-10-12 14:34 UTC, zktuong requested changes

2022-10-12 14:40 UTC, ktpolanski commented on container/dandelion_preprocess.py
> -        default="filtered",
or could change the test to go looking for filtered

2022-10-13 07:37 UTC, zktuong approved these changes

2022-10-13 07:37 UTC, merged